import { readFile, writeFile } from "node:fs/promises";

const schemaPath = new URL("../schemas/app-types.json", import.meta.url);
const outputPath = new URL("../src/lib/types.ts", import.meta.url);
const checkOnly = process.argv.includes("--check");

const schema = JSON.parse(await readFile(schemaPath, "utf8"));
const types = schema.types.map((type) => {
  if (type.alias) {
    return `export type ${type.name} = ${type.alias};`;
  }

  const fields = Object.entries(type.fields)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");
  const body = `{\n${fields}\n}`;
  return type.extends
    ? `export type ${type.name} = ${type.extends} & ${body};`
    : `export type ${type.name} = ${body};`;
});

const output = `// This file is generated by scripts/generate-types.mjs.\n// Edit schemas/app-types.json instead.\n\n${types.join("\n\n")}\n`;

if (checkOnly) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== output) {
    console.error("src/lib/types.ts is out of date. Run npm run generate:types.");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, output);
}
