import { readFile, writeFile } from "node:fs/promises";

const schemaPath = new URL("../schemas/app-types.json", import.meta.url);
const outputPath = new URL("../src/lib/types.ts", import.meta.url);

const schema = JSON.parse(await readFile(schemaPath, "utf8"));
const types = schema.types.map((type) => {
  const fields = Object.entries(type.fields)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");
  return `export type ${type.name} = {\n${fields}\n};`;
});

const output = `// This file is generated by scripts/generate-types.mjs.\n// Edit schemas/app-types.json instead.\n\n${types.join("\n\n")}\n`;

await writeFile(outputPath, output);
